//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        public int Id { get; set; }  

        [Required(ErrorMessage = "Tên đăng nhập không được để trống")]
        [DisplayName("Tên đăng nhập")]
        public string Username { get; set; }
         
        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage = "Mật khẩu không được để trống")]
        public string Password { get; set; }

        [DisplayName("Câu hỏi bảo mật")]
        [Required(ErrorMessage = "Bạn phải điền câu trả lời để phòng trường hợp quên mật khẩu")]
        public string Question { get; set; }
    }
}
