//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Họ và tên không được để trống")]
        [DisplayName("Họ và tên")]
        public string Name { get; set; }
         
        [DisplayName("Ngày sinh")]
        [Required(ErrorMessage = "Ngày sinh không được để trống")]
        public Nullable<System.DateTime> BirthDate { get; set; }

        [DisplayName("Địa chỉ")]
        [Required(ErrorMessage = "Địa chỉ không được để trống")]
        public string Address { get; set; }
          
        [DisplayName("Lớp")]  
        [Required(ErrorMessage = "Bạn phải chọn tên lớp")]
        public string Class { get; set; } 

        [DisplayName("Học lực")]
        [Required(ErrorMessage = "Bạn phải chọn học lực")] 
        public string Rank { get; set; }
    }
}
